name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: 91song4/cloudtype-test
          stage: main
          yaml: >
            name: cloudtype-test

            app: node@18

            options:
              env:
                - name: NODE_ENV
                  value: ${{secrets.NODE_ENV}}
                - name: DATABASE_HOST
                  value: ${{secrets.DATABASE_HOST}}
                - name: DATABASE_PORT
                  value: ${{secrets.DATABASE_PORT}}
                - name: DATABASE_USERNAME
                  value: ${{secrets.DATABASE_USERNAME}}
                - name: DATABASE_PASSWORD
                  value: ${{secrets.DATABASE_PASSWORD}}
                - name: DATABASE_NAME
                  value: ${{secrets.DATABASE_NAME}}
              ports: 3000
              build: npm run build
              start: npm run start:prod
              install: npm ci
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
